# Generated by Django 4.1.1 on 2022-09-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={"verbose_name": "Person", "verbose_name_plural": "People",},
        ),
    ]
