# Generated by Django 4.1.1 on 2022-09-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="first_name_en_us",
            field=models.CharField(max_length=30, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="person",
            name="first_name_ru",
            field=models.CharField(max_length=30, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="person",
            name="first_name_uz",
            field=models.CharField(max_length=30, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name_en_us",
            field=models.CharField(max_length=30, null=True, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name_ru",
            field=models.CharField(max_length=30, null=True, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name_uz",
            field=models.CharField(max_length=30, null=True, verbose_name="Last name"),
        ),
    ]
